import { css, html, type PropertyValues } from 'lit';
import { animate } from 'motion';
import { TarwadahElement, sharedStyles } from '../../shared/base';
import { watchScene } from '../../shared/motion';
export default class TarwadahFeatures extends TarwadahElement {
  protected section='features' as const;
  private stop?:()=>void;
  private widthAnimation?:ReturnType<typeof animate>;
  private photoAnimations:Array<ReturnType<typeof animate>>=[];
  static styles=[sharedStyles,css`
    .section{padding-top:130px}.layout{position:relative;height:calc(1327px + var(--feature-count,5)*620px - 132px)}.texts{position:absolute;inset-inline-start:61.32%;top:1327px;width:38.68%;z-index:1}.feature{height:620px;display:flex;flex-direction:column;padding-top:0px}.number{margin-bottom:16px;color:var(--tw-accent);font-family:'TW Roboto Mono',monospace;font-size:18px;line-height:1.4}h2{font-family:'TW Instrument',serif;font-size:44px;font-weight:400;letter-spacing:-.04em;line-height:1.1;max-width:301px}.description{font-family:'TW Roboto Mono',monospace;font-size:16px;line-height:1.2;letter-spacing:-.02em;max-width:301px;margin-top:16px;color:#bfbfbf}.photos{height:100svh;position:sticky;top:0;width:var(--photo-width,100%);overflow:hidden}.photos img{position:absolute;inset:-12px 0 auto;height:calc(100% + 24px);object-fit:cover;opacity:1;clip-path:inset(100% 0 0)}.photos img:first-child{clip-path:inset(0% 0 0);width:var(--intro-width,100%);max-width:none}.photos img:nth-child(3){top:-16px;height:calc(100% + 32px)}.photos img:nth-child(4){top:-17.5px;height:calc(100% + 35px)}.photos img:nth-child(5){top:-15.5px;height:calc(100% + 31px)}.intro,.mobile-image{display:none}
    @media(max-width:809px){.section{padding-block:150px 100px;height:auto}.intro,.photos,.mobile-image{display:none}.layout{height:auto;padding-inline:20px}.texts{position:static;width:100%}.feature{min-height:419.625px;padding-top:0}.feature:last-child{height:auto;min-height:0}h2{font-size:44px}.description{max-width:301px;font-size:16px}.number{margin-bottom:16px}}
  `];
  protected updated(changed:PropertyValues){super.updated(changed);this.style.setProperty('--feature-count',String(this.settings.items.length));}
  protected startMotion(){this.stop?.();this.widthAnimation?.stop();this.photoAnimations.forEach(a=>a.stop());this.photoAnimations=[];let narrow:boolean|undefined,previous=-1;this.stop=watchScene(this,()=>{const layout=this.renderRoot.querySelector('.layout')!;const top=layout.getBoundingClientRect().top;this.style.setProperty('--intro-width',this.getBoundingClientRect().width+'px');const next=matchMedia('(max-width:1199px)').matches||top+518<=innerHeight;const photos=this.renderRoot.querySelector<HTMLElement>('.photos')!;if(next!==narrow){const initial=narrow===undefined;narrow=next;this.widthAnimation?.stop();if(initial||matchMedia('(prefers-reduced-motion: reduce)').matches)photos.style.width=next?'50%':'100%';else this.widthAnimation=animate(photos,{width:next?'50%':'100%'},{duration:1.2,ease:[.61,0,.56,1]});}let active=0;this.renderRoot.querySelectorAll('.feature').forEach((feature,i)=>{if(feature.getBoundingClientRect().top<innerHeight*.5)active=i+1;});if(active!==previous){this.photoAnimations.forEach(a=>a.stop());const initial=previous===-1;previous=active;this.photoAnimations=[];this.renderRoot.querySelectorAll<HTMLElement>('.photos img').forEach((image,i)=>{const clip=i<=active?'inset(0% 0 0)':'inset(100% 0 0)';if(initial||matchMedia('(prefers-reduced-motion: reduce)').matches)image.style.clipPath=clip;else this.photoAnimations.push(animate(image,{clipPath:clip},{duration:1,ease:[.44,0,.56,1]}));});}this.dataset.activeImage=String(active);});}

  disconnectedCallback(){this.stop?.();this.widthAnimation?.stop();this.photoAnimations.forEach(a=>a.stop());super.disconnectedCallback();}
  render(){const s=this.settings;return html`<section class="section" aria-label=${s.label}><figure class="intro"><img src=${s.intro_image} alt=${s.label} loading="lazy"></figure><div class="layout"><div class="photos" aria-hidden="true"><img class="active" src=${s.intro_image} alt="" loading="lazy">${s.items.map((item:any)=>html`<img src=${item.image} alt="" loading="lazy">`)}</div><div class="texts">${s.items.map((item:any,i:number)=>html`<article class="feature" data-index=${i}><p class="number mono">[${i+1}]</p><h2>/ ${item.title}</h2><p class="description mono">${item.description}</p><img class="mobile-image" src=${item.image} alt=${item.title} loading="lazy"></article>`)}</div></div></section>`;}
}
