import { css, html } from 'lit';
import { TarwadahElement, sharedStyles } from '../../shared/base';
import { watchScene, springChannel } from '../../shared/motion';
import { targetProgress, reviewTravel } from '../../shared/reference-motion';
export default class TarwadahTestimonials extends TarwadahElement {
  protected section='testimonials' as const;
  private stop?:()=>void;
  private channels:Array<ReturnType<typeof springChannel>>=[];
  static styles=[sharedStyles,css`
    .section{position:relative;padding-block:180px 160px;overflow:hidden}.heading{max-width:516px;margin:auto;text-align:center}.eyebrow{font-family:'TW Instrument',serif;font-size:20px;line-height:24px;letter-spacing:-.02em;margin-bottom:4px;color:#bfbfbf}h2{font-size:48px;letter-spacing:-.06em;line-height:1;font-weight:500}.rows{margin-block:32px;position:relative;height:568px}.viewport{position:absolute;top:33px;inset-inline:0;height:240px;overflow:hidden;direction:ltr;mask-image:linear-gradient(to right,transparent,#000 6%,#000 94%,transparent)}.track{display:flex;width:max-content;gap:24px;will-change:transform}.viewport.reverse{top:297px;display:flex;justify-content:flex-end}.reverse .track{margin-right:-27px}.quote{width:409px;height:240px;border:1px solid #ffffff20;border-radius:2px;padding:40px;display:flex;flex-direction:column;background:#000}.quote-icon{display:block;width:20px;height:14px;flex:none;margin-bottom:28px;color:var(--tw-accent)}.quote blockquote{font-family:'TW Roboto Mono',monospace;font-size:18px;letter-spacing:-.02em;line-height:1.4;color:#bfbfbf}.quote figcaption{font-family:'TW Instrument',serif;font-size:20px;line-height:24px;letter-spacing:-.02em;color:#bfbfbf;margin-top:32px}.caption{text-align:end;padding-inline:56px;color:#bbb;font-family:'TW Roboto Mono',monospace;font-size:14px}
    @media(max-width:809px){.section{padding-block:180px 168px}.heading{padding-inline:20px;max-width:390px}h2{font-size:32px}.caption{padding-inline:20px}}
  `];
  protected startMotion(){this.stop?.();this.channels.forEach(c=>c.destroy());this.channels=[];this.renderRoot.querySelectorAll<HTMLElement>('.track').forEach((track,i)=>this.channels.push(springChannel(0,p=>track.style.transform='translateX('+reviewTravel(p)[i]+'px)',160,60)));this.stop=watchScene(this,()=>{const box=this.getBoundingClientRect();const p=matchMedia('(prefers-reduced-motion: reduce)').matches?0:targetProgress(box.top,box.height,innerHeight);this.channels.forEach(c=>c.set(p));this.dataset.motionProgress=p.toFixed(3);});}
  disconnectedCallback(){this.stop?.();this.channels.forEach(c=>c.destroy());super.disconnectedCallback();}
  render(){const s=this.settings;const middle=Math.ceil(s.items.length * 4/7);return html`<section class="section" aria-label=${s.eyebrow}><header class="heading"><p class="eyebrow">${s.eyebrow}</p><h2>${s.title}</h2></header><div class="rows">${[s.items.slice(0,middle),s.items.slice(middle)].map((items:any[],row:number)=>html`<div class="viewport ${row?'reverse':''}"><div class="track"><div style="display:flex;gap:24px">${items.map(item=>html`<figure class="quote"><svg class="quote-icon" aria-hidden="true" viewBox="0 0 20 14"><path d="M1.429 14H5.714L8.571 8.4V0H0V8.4H4.286ZM12.857 14H17.143L20 8.4V0H11.429V8.4H15.714Z" fill="currentColor"/></svg><blockquote>${item.quote}</blockquote><figcaption>— ${item.author}</figcaption></figure>`)}</div></div></div>`)}</div><p class="caption mono">${s.caption}</p></section>`;}
}
