import { css, html } from 'lit';
import { TarwadahElement, sharedStyles } from '../../shared/base';
import { TarwadahProductElement } from '../../shared/product';
import { watchScene } from '../../shared/motion';
export default class TarwadahProductStrip extends TarwadahProductElement {
  protected section = 'product-strip' as const;
  private stop?:()=>void;
  static styles = [sharedStyles, css`
    :host{position:relative;z-index:20}:host(.floating){position:fixed;bottom:20px;left:50%;transform:translateX(-50%);width:min(743px,calc(100% - 40px));background:transparent;opacity:0;pointer-events:none;transition:opacity .25s}:host(.floating.visible){opacity:1;pointer-events:auto}.bar{max-width:743px;margin:0 auto;display:flex;align-items:center;gap:24px;background:#101010e6;backdrop-filter:blur(20px);border:1px solid #ffffff0a;border-radius:4px;padding:18px 28px 18px 20px}.image{width:48px;height:48px;border:1px solid #ffffff18}h2{font-family:'TW Instrument',serif;font-size:20px;font-weight:400;line-height:24px;letter-spacing:-.02em;margin-bottom:2px;white-space:nowrap}.colors{color:var(--tw-accent);font-family:'TW Roboto Mono',monospace;font-size:14px;line-height:19px;white-space:nowrap}.price{margin-inline-start:auto;text-align:end}.price p{font-family:'TW Roboto Mono',monospace;font-size:16px;color:#7d7d7d;line-height:19px;margin-bottom:2px}.details{font-family:'TW Roboto Mono',monospace;font-size:16px;text-decoration:underline;text-underline-offset:3px;color:#bfbfbf;white-space:nowrap}.button{background:#252525;color:#bfbfbf;font-family:'TW Roboto Mono',monospace;padding:12px 28px;font-size:16px;border:1px solid #ffffff0a;border-radius:4px;white-space:nowrap}.down-arrow{display:none}.section{padding:0}
    @media(max-width:809px){:host(.floating){width:calc(100% - 40px);bottom:calc(16px + env(safe-area-inset-bottom,0px))}.bar{gap:12px;padding:12px 20px;height:77px}.image{width:45px;height:48px}h2{font-size:20px}.colors{font-size:14px}.price{display:none}.button,.button:hover{margin-inline-start:auto;font-size:0;padding:0;width:36px;height:36px;flex:0 0 36px;background:transparent;color:#bfbfbf;border:0;display:grid;place-items:center}.button span{display:none}.button .down-arrow{display:block;width:22px;height:22px;flex:none}.section{padding:0}}
  `];
  protected startMotion(){this.stop?.();this.stop=watchScene(document.body,()=>{const hero=document.querySelector<HTMLElement>('[data-section="hero"]');const buy=document.querySelector<HTMLElement>('[data-section="buy-now"]');const visible=!hero||(hero.getBoundingClientRect().top<-Math.min(800,innerHeight*.8)&&(!buy||buy.getBoundingClientRect().top>innerHeight*.65));this.classList.toggle('floating',!!hero);this.classList.toggle('visible',visible);this.inert=!visible;this.setAttribute('aria-hidden',String(!visible));});}
  disconnectedCallback(){this.stop?.();super.disconnectedCallback();}
  render(){const s=this.settings;const p=this.productData;const image=this.productId?p?.image?.url:s.image;return html`<aside class="section" aria-label=${p?.name||s.title}><div class="bar">${image?html`<img class="image" src=${image} alt=${p?.name||s.title} loading="lazy">`:''}<div><h2>${p?.name||s.title}</h2>${!this.productId?html`<p class="mono colors">${s.colors}</p>`:''}</div><div class="price"><p class="mono">${this.formattedPrice}</p><a class="mono details" href="#${s.target}" @click=${(e:Event)=>{e.preventDefault();this.jump(s.target)}}>${s.detail_label}</a></div><button class="button" @click=${()=>this.jump(s.target)}><span>${s.cta_label}</span><svg class="down-arrow" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M12 4v16m-6-6 6 6 6-6"/></svg></button></div></aside>`;}
}
